export const data = {
  products: [
    {
      id: "1",
      name: "Headphones Wireless",
      image: "/images/headphone-1.webp",
      oldPrice: 250.0,
      price: 120,
      countInStock: 200,
      rating: 4.5,
      numReviews: 10,
      description:
        "Experience unparalleled freedom and immersive sound with our Premium Wireless Headphones. These sleek and stylish headphones utilize the latest Bluetooth technology, allowing you to enjoy your favorite music and podcasts without being tethered by wires. Whether you're on a long commute, hitting the gym, or simply relaxing at home, these headphones deliver crystal-clear audio and deep, rich bass that will elevate your listening experience.\n\nKey Features:\n- Advanced Bluetooth 5.0 connectivity for seamless wireless audio\n- Noise-cancelling technology for a distraction-free environment\n- Up to 20 hours of battery life on a single charge\n- Ergonomically designed for all-day comfort\n- Intuitive touch controls for playback, volume, and calls\n- Foldable and portable design for easy storage and travel\n\nStep into the future of audio with our Premium Wireless Headphones. Upgrade your listening journey today!",
      category: "Headphone",
    },
    {
      id: "2",
      name: "Galaxy Android Tablet",
      image: "/images/mobile-1.webp",
      price: 399.99,
      countInStock: 5,
      rating: 4.0,
      numReviews: 10,
      description:
        "Discover limitless possibilities with the Samsung Galaxy Tab XE. This cutting-edge Android tablet offers a blend of power, versatility, and sleek design, making it the perfect companion for both work and play. Whether you're a creative professional, a student, or someone who loves entertainment on the go, the Galaxy Tab XE has you covered.\n\nKey Features:\n- Stunning 10.1-inch Super AMOLED display for vibrant visuals\n- Powerful octa-core processor for smooth multitasking\n- S Pen compatibility for precise note-taking and creative tasks\n- Long-lasting battery that keeps up with your day\n- DeX mode for a PC-like experience\n- Dolby Atmos speakers for immersive audio\n- Expandable storage for your apps, files, and media\n\nStay productive with seamless multitasking, enjoy immersive entertainment, and take your creativity to new heights with the Samsung Galaxy Tab XE. Elevate your tablet experience today!",
      category: "Tablets",
    },
    {
      id: "3",
      name: "Apple iPhone 14 Pro 256GB Zilver",
      image: "/images/iphone14.webp",
      oldPrice: 1500.0,
      price: 1394.99,
      countInStock: 15,
      rating: 4.5,
      numReviews: 14,
      description:
        "The new iPhone 14 reinvents the smartphone experience with its wide-ranging avant-garde features – from trailblazing life-saving safety innovations and the longest-running battery to a leading-edge camera and an incomparable display. Hold your horses, for there’s a lot more.",
      category: "Smartphone",
    },
    {
      id: "4",
      name: "Nikon Z-6 ii",
      image: "/images/nikon-z6-ii.webp",
      price: 2249,
      countInStock: 5,
      rating: 4.5,
      numReviews: 100,
      description:
        "It's a professional-grade full-frame mirrorless camera, period. From wedding photography to wildlife and landscape photography, and video/cinema, the Z6 II could be the best choice for you.",
      category: "Camera",
    },
    {
      id: "5",
      name: "Sony Smart Watch",
      image: "/images/watch-5.webp",
      price: 299.99,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      category: "watch",
    },
    {
      id: "6",
      name: "H.Koenig Electric Citrus Press",
      image: "/images/juicer-1.jpg",
      oldPrice: 89.99,
      price: 49.99,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description:
        "H.Koenig Electric Citrus Press with Professional Press Lever AGR80, 160W, BPA Free, Stainless Steel, Fast, Automatic, Quiet, Anti-drop, Dishwasher Resistant...",
      category: "kitchen Appliances",
    },
    {
      id: "7",
      name: "White Gold Plated Princess",
      image: "/images/ring.jpg",
      price: 79.99,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description:
        "Classic Created Wedding Engagement Solitaire Diamond Promise Ring for Her. Gifts to spoil your love more for Engagement, Wedding, Anniversary, Valentine's Day...",
      category: "Jewellery",
    },
    {
      id: "8",
      name: "LEGO 42137 Technic Formula E ",
      image: "/images/lego.jpg",
      price: 38.99,
      countInStock: 5,
      rating: 4.5,
      numReviews: 77,
      description:
        "LEGO 42137 Technic Formula E Porsche 99X Electric, Pull-back Racing Car Building Toy with AR App, Nice Gift for Kids",
      category: "Toys",
    },
  ],
};
